# Generated by Django 3.0.5 on 2020-12-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_auto_20201222_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='summary',
            field=models.CharField(max_length=2000),
        ),
    ]
